check for SDL_image and SDL_gfx libs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -579,6 +579,30 @@ check_libconfig $sdlconfig SDL_Init ||
 } || die "Error, can't find libsdl !"
 
 #################################################
+#   check for SDL_image
+#################################################
+echolog "Checking for libsdl_image ..."
+{
+  if [ -n "$sdlprefix" ]; then
+    check_cflags -I$sdlprefix/include
+    check_ldflags -L$sdlprefix/lib
+  fi
+  check_lib SDL/SDL_image.h IMG_Load -lSDL_image;
+} || die "Error, can't find libsdl_image !"
+
+#################################################
+#   check for SDL_gfx
+#################################################
+echolog "Checking for libsdl_gfx ..."
+{
+  if [ -n "$sdlprefix" ]; then
+    check_cflags -I$sdlprefix/include
+    check_ldflags -L$sdlprefix/lib
+  fi
+  check_lib SDL/SDL_rotozoom.h zoomSurface -lSDL_gfx;
+} || die "Error, can't find libsdl_gfx !"
+
+#################################################
 #   check for libcurl
 #################################################
 #echolog "Checking for libcurl ..."
